Задача №2. Работа с массивами и объектами
js-tasks-ru/js-20220418_bekeshkin pull request #2
Opened 2022-04-27 02:57 UTC by bekeshkin

2022-04-27 02:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 17:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-27 21:59 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-28 11:37 UTC, dragozin requested changes
Нужно немного доработать реализацию `pick`

2022-04-28 11:37 UTC, dragozin commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let multiplier = param === "asc" ? 1 : -1;
Лучше обработать не корректное значение аргумента `param`
Представьте, что разработчик ошибся и вместо 'desc' передал 'decs' и будет ожидать что массив отсортируется по убыванию. И такая небольшая ошибка может стоить разработчику времени для отладки.
Как совет: лучше выбросить явную ошибку, если пришло не корректное значение параметра.

2022-04-28 11:37 UTC, dragozin commented on 02-javascript-data-types/2-pick/index.js
> +  fields.forEach(f => newObject[f] = obj[f]);
Решение не корректное. Цикл заберет даже те свойства, которые отсутствуют в объекте obj. Их значения в результирующем объекте будут хранить undefined.

2022-04-28 11:37 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let index = path.indexOf('.');
index не меняется, лучше использовать константу

2022-04-28 11:37 UTC, dragozin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    propValue = path.substring(0, path.indexOf('.')); // пример: 'name1'
операцию `path.indexOf('.')` можно не вычислять, т.к. значение уже хранится в переменной index

2022-04-28 15:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-28 17:43 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-29 13:05 UTC, dragozin requested changes
Привет!
поправь, пожалуйста, реализацию задачки pick

подробнее тут: https://github.com/js-tasks-ru/js-20220418_bekeshkin/pull/2#discussion_r860752820

2022-04-29 13:17 UTC, jsru commented
Добавляю преподавателя (@dragozin) для код-ревью.

2022-04-29 13:28 UTC, bekeshkin commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let multiplier = param === "asc" ? 1 : -1;
готово

2022-04-29 13:29 UTC, bekeshkin commented on 02-javascript-data-types/2-pick/index.js
> +  fields.forEach(f => newObject[f] = obj[f]);
готово

2022-04-29 13:29 UTC, bekeshkin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let index = path.indexOf('.');
готово

2022-04-29 13:29 UTC, bekeshkin commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    propValue = path.substring(0, path.indexOf('.')); // пример: 'name1'
готово

2022-04-29 14:55 UTC, dragozin approved these changes
Отлично!

2022-04-29 14:56 UTC, merged